// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostAggregatedService.DataLayer;

namespace PostAggregatedService.Migrations
{
    [DbContext(typeof(PostAggregatedDbContext))]
    [Migration("20210819204352_postaggregatedSeedDb")]
    partial class postaggregatedSeedDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PostAggregatedService.Entities.PostAggregated", b =>
                {
                    b.Property<Guid>("PostAggregatedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfComments")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfDislikes")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfHearts")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLikes")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSmileys")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfVisits")
                        .HasColumnType("int");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostAggregatedId");

                    b.ToTable("PostAggregated");

                    b.HasData(
                        new
                        {
                            PostAggregatedId = new Guid("d221da3e-f9d5-45d5-a44c-15479d3b7b21"),
                            NumberOfComments = 10,
                            NumberOfDislikes = 5,
                            NumberOfHearts = 6,
                            NumberOfLikes = 10,
                            NumberOfSmileys = 1,
                            NumberOfVisits = 100,
                            PostId = new Guid("71a1d81c-7fea-4e9a-bb29-541e165fc198")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
